name = "jahitan-app"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

# Binding database D1. Setelah membuat database dengan
# `wrangler d1 create jahitan-db`, salin "database_id" yang
# ditampilkan ke bawah ini. Lihat README.md untuk langkah lengkap.
[[d1_databases]]
binding = "DB"
database_name = "jahitan-db"
database_id = "bc4c2ae7-d593-4887-9863-26b344d92c10"
